/**
 * Drive-backed `HydrationBundleDrive` — persists Airtable NDJSON hydration
 * bundles through the same n8n `/webhook/eo-store` proxy that the EoStore
 * uses for encrypted blob writes.
 *
 * Shape on Drive (per import):
 *
 *   airtable-hydration-<importId>.manifest.json
 *     ↳ AES-GCM(BlobEnvelope) over the small JSON manifest below.
 *
 *   airtable-hydration-<importId>.part-0000.json
 *   airtable-hydration-<importId>.part-0001.json
 *   …
 *     ↳ AES-GCM(BlobEnvelope) over a gzipped slice of the original NDJSON.
 *       Slices are cut at `\n` boundaries so every part is itself a valid
 *       NDJSON prefix — handy for offline triage but not relied on for
 *       reassembly.
 *
 * The hydration bundle is otherwise **public-ish data** (whatever the user
 * already has API access to in Airtable), but per the project requirement
 * everything that touches Drive goes through the EoStore key — same envelope
 * version, key id, IV, content hash, and gzip flow as
 * `eodb-blob-writer.ts:194-232`.
 *
 * Why chunked: the proxy at `eodb-blob-endpoint.ts:22` enforces a 20 s
 * timeout per request and was sized for small EoStore writes. A 500 MB
 * single-shot upload would almost certainly time out at the proxy or the
 * fronting nginx layer. 32 MB ciphertext chunks keep each round-trip well
 * under that budget and let a single failed chunk retry independently.
 */

import { base64ToBuffer, bufferToBase64, getKeyById, resolveSnapshotKeyId } from '../crypto/segment-keys';
import type { LocalKeyring } from '../db/crypto-types';
import {
  fetchBlobFromDrive,
  gunzipBytes,
  gzipBytes,
  storeBlobToDrive,
  type BlobEnvelope,
  type BlobUploadMeta,
} from '../storage/eodb-blob-endpoint';
import {
  HYDRATION_BUNDLE_FORMAT,
  HYDRATION_BUNDLE_VERSION,
  type HydrationBundleHeader,
} from './airtable-hydration-bundle';
import type { HydrationBundleDrive } from './airtable-resumable-hydration';

/** Plaintext bytes per chunk before gzip + AES-GCM. ~32 MB. */
const CHUNK_PLAINTEXT_BYTES = 32 * 1024 * 1024;

const FILENAME_RE = /^airtable-hydration-(.+)\.ndjson$/;

interface ChunkRecord {
  index: number;
  dataId: string;
  plaintextSize: number;
  contentHash: string;
}

interface BundleManifest {
  format: typeof HYDRATION_BUNDLE_FORMAT;
  version: typeof HYDRATION_BUNDLE_VERSION;
  importId: string;
  byteLength: number;
  chunkCount: number;
  /** Duplicated here so a future session can preview without downloading chunks. */
  header: HydrationBundleHeader;
  chunks: ChunkRecord[];
}

export interface HydrationBundleDriveDeps {
  matrixToken: string;
  spaceRoomId: string;
  /**
   * Lazy keyring loader — the encryption key isn't needed until the first
   * upload/download, and pulling it on construction would force callers to
   * thread async setup through their effects.
   */
  loadKeyring: () => Promise<LocalKeyring>;
  /**
   * Optional progress hook fired as chunks upload/download. Useful so a 500 MB
   * import can show "chunk 7/16 uploaded" instead of a frozen spinner for a
   * minute and a half.
   */
  onProgress?: (p: HydrationBundleDriveProgress) => void;
}

export interface HydrationBundleDriveProgress {
  phase: 'uploading' | 'downloading';
  chunkIndex: number;
  chunkCount: number;
  bytesDone: number;
  bytesTotal: number;
}

export function createHydrationBundleDrive(
  deps: HydrationBundleDriveDeps,
): HydrationBundleDrive {
  return new ChunkedDriveBackend(deps);
}

class ChunkedDriveBackend implements HydrationBundleDrive {
  constructor(private deps: HydrationBundleDriveDeps) {}

  async uploadHydrationBundle(
    bytes: Uint8Array,
    opts: { fileName: string; importId: string },
  ): Promise<{ fileName: string; driveFileId: string; byteSize: number }> {
    const header = readHeader(bytes);
    if (header.importId !== opts.importId) {
      // Trust the bundle's own header — the resumable orchestrator passes the
      // checkpoint's importId, but if a user re-imports a bundle generated by
      // a different tool the in-file id is the source of truth.
      opts = { ...opts, importId: header.importId };
    }

    const { key, keyId } = await this.resolveKey();
    const slices = sliceAtLineBoundaries(bytes, CHUNK_PLAINTEXT_BYTES);
    const chunks: ChunkRecord[] = [];

    for (let i = 0; i < slices.length; i++) {
      const slice = slices[i];
      const dataId = chunkDataId(opts.importId, i);
      const contentHash = await sha256hex(slice);
      const ciphertext = await encryptChunk(slice, key);
      const meta: BlobUploadMeta = {
        v: 2,
        iv: ciphertext.ivB64,
        content_hash: contentHash,
        key_id: keyId,
        plaintext_size: slice.byteLength,
        compression: 'gzip',
      };
      await storeBlobToDrive(
        this.deps.matrixToken,
        dataId,
        meta,
        ciphertext.ct,
        this.deps.spaceRoomId,
      );
      chunks.push({
        index: i,
        dataId,
        plaintextSize: slice.byteLength,
        contentHash,
      });
      this.deps.onProgress?.({
        phase: 'uploading',
        chunkIndex: i + 1,
        chunkCount: slices.length,
        bytesDone: chunks.reduce((a, c) => a + c.plaintextSize, 0),
        bytesTotal: bytes.byteLength,
      });
    }

    const manifest: BundleManifest = {
      format: HYDRATION_BUNDLE_FORMAT,
      version: HYDRATION_BUNDLE_VERSION,
      importId: opts.importId,
      byteLength: bytes.byteLength,
      chunkCount: chunks.length,
      header,
      chunks,
    };
    const manifestBytes = new TextEncoder().encode(JSON.stringify(manifest));
    const manifestHash = await sha256hex(manifestBytes);
    const manifestCipher = await encryptChunk(manifestBytes, key);
    const manifestMeta: BlobUploadMeta = {
      v: 2,
      iv: manifestCipher.ivB64,
      content_hash: manifestHash,
      key_id: keyId,
      plaintext_size: manifestBytes.byteLength,
      compression: 'gzip',
    };
    const manifestStored = await storeBlobToDrive(
      this.deps.matrixToken,
      manifestDataId(opts.importId),
      manifestMeta,
      manifestCipher.ct,
      this.deps.spaceRoomId,
    );

    return {
      fileName: opts.fileName,
      driveFileId: manifestStored.fileId,
      byteSize: bytes.byteLength,
    };
  }

  async downloadHydrationBundle(fileName: string): Promise<Uint8Array | null> {
    const importId = importIdFromFileName(fileName);
    if (!importId) return null;

    const manifestFetch = await fetchBlobFromDrive(
      this.deps.matrixToken,
      manifestDataId(importId),
      this.deps.spaceRoomId,
    );
    if (!manifestFetch) return null;

    const { key } = await this.resolveKey();
    const manifestBytes = await decryptEnvelope(manifestFetch.envelope, key);
    let manifest: BundleManifest;
    try {
      manifest = JSON.parse(new TextDecoder().decode(manifestBytes)) as BundleManifest;
    } catch (e) {
      throw new Error(
        `hydration bundle manifest at ${manifestFetch.uri} is corrupt: ${(e as Error).message}`,
      );
    }
    if (manifest.format !== HYDRATION_BUNDLE_FORMAT) {
      throw new Error(`unexpected manifest format: ${String(manifest.format)}`);
    }

    const out = new Uint8Array(manifest.byteLength);
    let offset = 0;
    for (const chunk of manifest.chunks) {
      const fetched = await fetchBlobFromDrive(
        this.deps.matrixToken,
        chunk.dataId,
        this.deps.spaceRoomId,
      );
      if (!fetched) {
        throw new Error(`hydration bundle chunk ${chunk.index} (${chunk.dataId}) not found on Drive`);
      }
      const plain = await decryptEnvelope(fetched.envelope, key);
      const observed = await sha256hex(plain);
      if (observed !== chunk.contentHash) {
        throw new Error(
          `hydration bundle chunk ${chunk.index} content hash mismatch — expected ${chunk.contentHash}, got ${observed}`,
        );
      }
      if (offset + plain.byteLength > out.byteLength) {
        throw new Error(
          `hydration bundle chunk ${chunk.index} overflows declared byteLength (${manifest.byteLength})`,
        );
      }
      out.set(plain, offset);
      offset += plain.byteLength;
      this.deps.onProgress?.({
        phase: 'downloading',
        chunkIndex: chunk.index + 1,
        chunkCount: manifest.chunks.length,
        bytesDone: offset,
        bytesTotal: manifest.byteLength,
      });
    }
    if (offset !== manifest.byteLength) {
      throw new Error(
        `hydration bundle chunks total ${offset} bytes, manifest declared ${manifest.byteLength}`,
      );
    }
    return out;
  }

  private async resolveKey(): Promise<{ key: CryptoKey; keyId: string }> {
    const keyring = await this.deps.loadKeyring();
    const keyId = resolveSnapshotKeyId(keyring);
    if (!keyId) {
      throw new Error(
        'No encryption key in keyring — hydration bundles cannot be persisted to Drive until key delivery completes',
      );
    }
    const entry = getKeyById(keyring, keyId);
    if (!entry) throw new Error('Keyring missing resolved key');
    return { key: entry.key, keyId };
  }
}

// ─── Helpers ───────────────────────────────────────────────────────────────

function chunkDataId(importId: string, index: number): string {
  return `airtable-hydration-${importId}.part-${index.toString().padStart(4, '0')}`;
}

function manifestDataId(importId: string): string {
  return `airtable-hydration-${importId}.manifest`;
}

function importIdFromFileName(fileName: string): string | null {
  const m = FILENAME_RE.exec(fileName);
  return m ? m[1] : null;
}

/**
 * Read the first NDJSON line as the bundle header. Used to extract the
 * importId + manifest before the upload loop starts; throws if the bundle
 * doesn't open with a valid `eo-hydration-bundle` header.
 */
function readHeader(bytes: Uint8Array): HydrationBundleHeader {
  const newline = bytes.indexOf(0x0a);
  if (newline < 0) throw new Error('hydration bundle has no header line');
  const firstLine = new TextDecoder().decode(bytes.subarray(0, newline));
  let parsed: unknown;
  try {
    parsed = JSON.parse(firstLine);
  } catch (e) {
    throw new Error(`hydration bundle header is not JSON: ${(e as Error).message}`);
  }
  if (
    !parsed ||
    typeof parsed !== 'object' ||
    (parsed as { type?: unknown }).type !== 'header'
  ) {
    throw new Error('hydration bundle does not start with a header line');
  }
  const header = parsed as HydrationBundleHeader;
  if (header.format !== HYDRATION_BUNDLE_FORMAT) {
    throw new Error(`unexpected bundle format: ${String(header.format)}`);
  }
  return header;
}

/**
 * Cut `bytes` into pieces no larger than `maxBytes`, with each cut placed
 * immediately after the last `\n` that fits in the window. Keeps every chunk
 * a valid NDJSON prefix and never splits a record across two chunks.
 */
function sliceAtLineBoundaries(bytes: Uint8Array, maxBytes: number): Uint8Array[] {
  if (bytes.byteLength === 0) return [];
  const out: Uint8Array[] = [];
  let start = 0;
  while (start < bytes.byteLength) {
    const remaining = bytes.byteLength - start;
    if (remaining <= maxBytes) {
      out.push(bytes.subarray(start));
      break;
    }
    let cut = -1;
    // Walk backward from `start + maxBytes` looking for a newline. The bundle
    // writer always terminates each line with `\n`, so a window this size will
    // always contain at least one — except in pathological inputs where a
    // single line exceeds the chunk size, in which case we bail out and let
    // the chunk grow.
    for (let i = start + maxBytes - 1; i > start; i--) {
      if (bytes[i] === 0x0a) {
        cut = i + 1;
        break;
      }
    }
    if (cut < 0) {
      // Line larger than CHUNK_PLAINTEXT_BYTES — find the next newline forward
      // and emit an over-size chunk rather than corrupting the stream.
      const next = bytes.indexOf(0x0a, start + maxBytes);
      cut = next < 0 ? bytes.byteLength : next + 1;
    }
    out.push(bytes.subarray(start, cut));
    start = cut;
  }
  return out;
}

async function encryptChunk(
  plain: Uint8Array,
  key: CryptoKey,
): Promise<{ ct: Uint8Array; ivB64: string }> {
  const compressed = await gzipBytes(plain);
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const ctBuf = await crypto.subtle.encrypt(
    { name: 'AES-GCM', iv },
    key,
    compressed as unknown as ArrayBuffer,
  );
  return {
    ct: new Uint8Array(ctBuf),
    ivB64: bufferToBase64(iv),
  };
}

async function decryptEnvelope(envelope: BlobEnvelope, key: CryptoKey): Promise<Uint8Array> {
  const iv = base64ToBuffer(envelope.iv);
  const ct = base64ToBuffer(envelope.ct);
  const plainBuf = await crypto.subtle.decrypt(
    { name: 'AES-GCM', iv: iv as unknown as BufferSource },
    key,
    ct as unknown as ArrayBuffer,
  );
  const plain = new Uint8Array(plainBuf);
  if (envelope.compression === 'gzip') {
    return await gunzipBytes(plain);
  }
  return plain;
}

async function sha256hex(data: Uint8Array): Promise<string> {
  const hash = new Uint8Array(
    await crypto.subtle.digest('SHA-256', data as unknown as BufferSource),
  );
  let hex = '';
  for (let i = 0; i < hash.length; i++) hex += hash[i].toString(16).padStart(2, '0');
  return hex;
}
